name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, linter
      run: |
        npm ci
        npm run eslint
    - name: test
      run:  npm run test-headless
    - name: build
      run: npm run build
    - name: copy-files
      run:  cp -r ./dist ./server
    - name: clean-up
      run: |
        shopt -s extglob
        rm -r !(server)
        ls
    - name: Add changes to Git tracking
      run:  |
        git config user.email "icherhina@gmail.com"
        git config user.name "actions"
        git push --delete pr-pages
        git checkout -b pr-pages
        git add -A
        git commit -m release
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: pr-pages
